"""Reduce cognitive tasks"""

from .reduce import (
    ReduceTaskParameters,
    DMTaskParameters,
    RomoTaskParameters,
    CtxDMTaskParameters,
    DMTaskRandomModParameters,
    RomoTaskRandomModParameters,
    ReduceTaskCognitive,
    DMTask,
    DMTaskRandomMod,
    DMTask1,
    DMTask2,
    RomoTask,
    RomoTaskRandomMod,
    RomoTask1,
    RomoTask2,
    CtxDMTask,
    CtxDM1,
    CtxDM2,
    MultyReduceTasks,
)

__all__ = [
    "ReduceTaskParameters",
    "DMTaskParameters",
    "RomoTaskParameters",
    "CtxDMTaskParameters",
    "DMTaskRandomModParameters",
    "RomoTaskRandomModParameters",
    "ReduceTaskCognitive",
    "DMTask",
    "DMTaskRandomMod",
    "DMTask1",
    "DMTask2",
    "RomoTask",
    "RomoTaskRandomMod",
    "RomoTask1",
    "RomoTask2",
    "CtxDMTask",
    "CtxDM1",
    "CtxDM2",
    "MultyReduceTasks",
]
