# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Activate env
        run: |
          pytnon -m venv env
          source env/bin/activate
      - name: Install requirements
        run: |
          pip3 install -r requirements.txt
      
      - name: Install pytest
        run: |
          pip3 install pytest
          
      - name: Start tests
        run: |
          pytest
