# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  test:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install requirements
        run: |
          python -m pip install torch==1.10.1+cpu torchvision==0.11.2+cpu torchaudio==0.10.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
          #python -m pip install torch
          python -m pip install -r requirements.txt
          # git clone https://github.com/norse/norse.git && cd norse && python setup.py install && cd ..
          git clone https://github.com/Pugavkomm/norse && cd norse && python setup.py install && cd ..
          python -m pip install pytest
      - name: Pytest
        run: pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./cgtasknet"
